version: '3'
services:
  web:
    # Replace username/repo:tag with your name and image details.
    image: 'donizero8/flask_docker:version-0.0.3'
    ports:
      - '8888:5000'
    networks:
      - 'webnet'
  redis:
    image: redis
    networks:
      - 'webnet'
networks:
  webnet: